export interface Shop {
  id: string
  name: string
  owner: string
  description: string
  category: string
  image: string
  rating: number
  reviewCount: number
  location: string
  products: Product[]
}

export interface Product {
  id: string
  shopId: string
  name: string
  price: number
  description: string
  image: string
  category: string
  inStock: boolean
  details: string[]
  size?: "small" | "medium" | "large" | "tall" | "wide"
}

export interface CartItem {
  product: Product
  quantity: number
  shop: Shop
}

export const shops: Shop[] = [
  {
    id: "1",
    name: "Kultura Filipino Crafts",
    owner: "Maria Clara",
    description:
      "Authentic Filipino handicrafts, souvenirs, and traditional clothing showcasing the best of Filipino artistry.",
    category: "Handicrafts",
    image: "/filipino-traditional-crafts-handicrafts-shop-woode.jpg",
    rating: 4.9,
    reviewCount: 342,
    location: "Intramuros, Manila",
    products: [
      {
        id: "p1",
        shopId: "1",
        name: "Classic Barong Tagalog",
        price: 2500.0,
        description: "Traditional formal embroidered shirt made from pineapple fiber (piña).",
        image: "/barong-tagalog-embroidered-formal-shirt-traditiona.jpg",
        category: "Clothing",
        inStock: true,
        details: ["Hand-embroidered", "Piña-Jusi fabric", "Formal wear"],
        size: "medium",
      },
      {
        id: "p2",
        shopId: "1",
        name: "Capiz Shell Parol",
        price: 1800.0,
        description: "Traditional star-shaped lantern made of capiz shells, perfect for Christmas.",
        image: "/capiz-shell-parol-star-lantern-filipino-christmas-.jpg",
        category: "Decor",
        inStock: true,
        details: ["Handcrafted", "LED lights included", "24 inches diameter"],
        size: "large",
      },
      {
        id: "p3",
        shopId: "1",
        name: "Abaca Tote Bag",
        price: 450.0,
        description: "Eco-friendly tote bag woven from durable abaca fibers.",
        image: "/abaca-woven-tote-bag-natural-eco-friendly-filipino.jpg",
        category: "Accessories",
        inStock: true,
        details: ["Natural dye", "Leather handles", "Spacious interior"],
        size: "medium",
      },
      {
        id: "p4",
        shopId: "1",
        name: "Banig Sleeping Mat",
        price: 850.0,
        description: "Colorful handwoven sleeping mat from Samar.",
        image: "/banig-woven-sleeping-mat-filipino-colorful-pattern.jpg",
        category: "Home",
        inStock: true,
        details: ["Tikog grass", "Cool to sleep on", "Intricate patterns"],
        size: "large",
      },
      {
        id: "p5",
        shopId: "1",
        name: "Palawan South Sea Pearls",
        price: 3500.0,
        description: "Elegant gold stud earrings with genuine South Sea pearls.",
        image: "/south-sea-pearl-earrings-gold-studs-palawan-luxury.jpg",
        category: "Jewelry",
        inStock: true,
        details: ["18k Gold settings", "Authentic pearls", "Certificate of authenticity"],
        size: "small",
      },
      {
        id: "p6",
        shopId: "1",
        name: "Jeepney Die-Cast Model",
        price: 350.0,
        description: "Miniature replica of the iconic Philippine Jeepney.",
        image: "/jeepney-die-cast-model-souvenir-philippine-iconic.jpg",
        category: "Souvenirs",
        inStock: true,
        details: ["Metal alloy", "Hand-painted", "Collectible item"],
        size: "small",
      },
    ],
  },
  {
    id: "2",
    name: "Batangas Brews & Beans",
    owner: "Mang Jose",
    description: "Strong and aromatic coffee beans sourced directly from farmers in Lipa, Batangas.",
    category: "Coffee & Food",
    image: "/filipino-coffee-beans-batangas-liberica-coffee-sho.jpg",
    rating: 4.8,
    reviewCount: 189,
    location: "Lipa City, Batangas",
    products: [
      {
        id: "p7",
        shopId: "2",
        name: "Kapeng Barako (Ground)",
        price: 350.0,
        description: "Authentic Liberica coffee with a strong, bold flavor.",
        image: "/kapeng-barako-ground-coffee-batangas-liberica-dark.jpg",
        category: "Coffee",
        inStock: true,
        details: ["500g pack", "Dark roast", "Freshly ground"],
        size: "medium",
      },
      {
        id: "p8",
        shopId: "2",
        name: "Tablea de Cacao",
        price: 180.0,
        description: "Pure cacao tablets for making traditional hot chocolate (tsokolate).",
        image: "/tablea-cacao-chocolate-tablets-filipino-tsokolate.jpg",
        category: "Food",
        inStock: true,
        details: ["100% Pure Cacao", "No sugar added", "Pack of 10 rolls"],
        size: "small",
      },
      {
        id: "p9",
        shopId: "2",
        name: "Civet Coffee (Kape Alamid)",
        price: 1500.0,
        description: "Rare and exotic coffee made from beans eaten and excreted by civet cats.",
        image: "/kape-alamid-civet-coffee-premium-rare-luxury.jpg",
        category: "Coffee",
        inStock: true,
        details: ["100g jar", "Smooth taste", "Ethically sourced"],
        size: "small",
      },
      {
        id: "p10",
        shopId: "2",
        name: "Batangas Pure Honey",
        price: 250.0,
        description: "Raw, wild honey harvested from the forests of Batangas.",
        image: "/raw-wild-honey-batangas-pure-natural-bee-honey-bot.jpg",
        category: "Food",
        inStock: true,
        details: ["Unpasteurized", "350ml bottle", "Wild harvested"],
        size: "medium",
      },
      {
        id: "p11",
        shopId: "2",
        name: "Wooden Coffee Scoop",
        price: 80.0,
        description: "Hand-carved wooden scoop for your coffee beans.",
        image: "/hand-carved-wooden-coffee-scoop-acacia-wood.jpg",
        category: "Accessories",
        inStock: true,
        details: ["Acacia wood", "Food safe finish", "1 tbsp capacity"],
        size: "small",
      },
      {
        id: "p12",
        shopId: "2",
        name: "Kapeng Barako Beans",
        price: 320.0,
        description: "Whole roasted Liberica beans for grinding at home.",
        image: "/whole-roasted-coffee-beans-liberica-kapeng-barako.jpg",
        category: "Coffee",
        inStock: true,
        details: ["500g pack", "Whole bean", "Aromatic"],
        size: "medium",
      },
    ],
  },
  {
    id: "3",
    name: "Cebu Lechon & Delicacies",
    owner: "Aling Puring",
    description: "Famous delicacies from the Queen City of the South, delivered to your doorstep.",
    category: "Food",
    image: "/cebu-lechon-delicacies-filipino-food-shop-traditio.jpg",
    rating: 4.7,
    reviewCount: 521,
    location: "Carcar, Cebu",
    products: [
      {
        id: "p13",
        shopId: "3",
        name: "Dried Mangoes",
        price: 220.0,
        description: "Sweet and chewy dried mango slices from Cebu.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks",
        inStock: true,
        details: ["Export quality", "200g pack", "Sweet & tangy"],
        size: "medium",
      },
      {
        id: "p14",
        shopId: "3",
        name: "Otap Puff Pastry",
        price: 120.0,
        description: "Crispy, flaky, and sugary oval-shaped puff pastry.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks",
        inStock: true,
        details: ["Original flavor", "Great with coffee", "Fragile handling"],
        size: "small",
      },
      {
        id: "p15",
        shopId: "3",
        name: "Rosquillos",
        price: 150.0,
        description: "Ring-shaped cookies that are a Cebuano favorite.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks",
        inStock: true,
        details: ["Crunchy", "Lightly sweet", "Pasalubong favorite"],
        size: "medium",
      },
      {
        id: "p16",
        shopId: "3",
        name: "Chorizo de Cebu",
        price: 180.0,
        description: "Sweet and spicy native sausages, best fried.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Food",
        inStock: true,
        details: ["1 dozen", "Vacuum sealed", "Keep frozen"],
        size: "medium",
      },
      {
        id: "p17",
        shopId: "3",
        name: "Danggit (Dried Fish)",
        price: 350.0,
        description: "Salted and sun-dried rabbitfish, perfect for breakfast.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Food",
        inStock: true,
        details: ["Unsalted variant", "Crispy when fried", "250g pack"],
        size: "medium",
      },
      {
        id: "p18",
        shopId: "3",
        name: "Ampao (Rice Krispies)",
        price: 80.0,
        description: "Sweet puffed rice bars with peanuts.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Snacks",
        inStock: true,
        details: ["Carcar specialty", "Crispy", "Pack of 10"],
        size: "small",
      },
    ],
  },
  {
    id: "4",
    name: "Marikina Shoe Hub",
    owner: "Mang Rolando",
    description: "World-class quality footwear handcrafted by Marikina's finest shoemakers.",
    category: "Fashion",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.6,
    reviewCount: 112,
    location: "Marikina City",
    products: [
      {
        id: "p19",
        shopId: "4",
        name: "Leather Sandals",
        price: 850.0,
        description: "Durable and stylish genuine leather sandals for men.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Footwear",
        inStock: true,
        details: ["Genuine cowhide", "Rubber sole", "Hand-stitched"],
        size: "medium",
      },
      {
        id: "p20",
        shopId: "4",
        name: "School Shoes (Black)",
        price: 1200.0,
        description: "Classic black leather shoes for students.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Footwear",
        inStock: true,
        details: ["Durable leather", "Comfort insole", "Standard school regulation"],
        size: "medium",
      },
      {
        id: "p21",
        shopId: "4",
        name: "Marikina Loafers",
        price: 1500.0,
        description: "Comfortable slip-on loafers for casual or office wear.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Footwear",
        inStock: true,
        details: ["Soft leather", "Penny loafer style", "Available in brown/black"],
        size: "medium",
      },
      {
        id: "p22",
        shopId: "4",
        name: "Faux Snake Skin Boots",
        price: 2200.0,
        description: "Stylish ankle boots with a snake skin texture.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Footwear",
        inStock: true,
        details: ["Synthetic leather", "High heel", "Side zipper"],
        size: "medium",
      },
      {
        id: "p23",
        shopId: "4",
        name: "Leather Belt",
        price: 450.0,
        description: "Full grain leather belt to match your shoes.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Accessories",
        inStock: true,
        details: ["Genuine leather", "Heavy duty buckle", "Adjustable length"],
        size: "large",
      },
      {
        id: "p24",
        shopId: "4",
        name: "Canvas Sneakers",
        price: 950.0,
        description: "Locally made canvas sneakers, comfortable for daily use.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Footwear",
        inStock: true,
        details: ["Canvas upper", "Vulcanized rubber sole", "Unisex design"],
        size: "medium",
      },
    ],
  },
  {
    id: "5",
    name: "Baguio Weaves & Greens",
    owner: "Manang Imee",
    description: "Fresh produce and traditional weaves from the Summer Capital of the Philippines.",
    category: "Regional Specialties",
    image: "/placeholder.svg?height=300&width=400",
    rating: 5.0,
    reviewCount: 245,
    location: "Baguio City",
    products: [
      {
        id: "p25",
        shopId: "5",
        name: "Inabel Blanket",
        price: 1200.0,
        description: "Handwoven Ilocano blanket known for its durability and warmth.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Home",
        inStock: true,
        details: ["Cotton blend", "Traditional patterns", "Queen size"],
        size: "large",
      },
      {
        id: "p26",
        shopId: "5",
        name: "Strawberry Jam",
        price: 250.0,
        description: "Homemade jam with whole strawberries from La Trinidad.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Food",
        inStock: true,
        details: ["Whole berries", "Less sugar", "12oz jar"],
        size: "medium",
      },
      {
        id: "p27",
        shopId: "5",
        name: "Ube Jam (Halaya)",
        price: 320.0,
        description: "Creamy purple yam jam, a classic Baguio pasalubong.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Food",
        inStock: true,
        details: ["Real Ube", "Creamy texture", "Good Shepherd style"],
        size: "medium",
      },
      {
        id: "p28",
        shopId: "5",
        name: "Pine Wood Carving",
        price: 450.0,
        description: "Intricate wood carving of an eagle made from Benguet pine.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Decor",
        inStock: true,
        details: ["Hand-carved", "Varnished", "Desk display size"],
        size: "small",
      },
      {
        id: "p29",
        shopId: "5",
        name: "Fresh Strawberries",
        price: 400.0,
        description: "Basket of freshly picked sweet strawberries.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Food",
        inStock: true,
        details: ["1kg basket", "Sweet variety", "Farm fresh"],
        size: "medium",
      },
      {
        id: "p30",
        shopId: "5",
        name: "Sagada Oranges",
        price: 150.0,
        description: "Sweet and juicy oranges grown in the highlands of Sagada.",
        image: "/placeholder.svg?height=300&width=300",
        category: "Food",
        inStock: true,
        details: ["1kg pack", "Seedless variety", "Vitamin C rich"],
        size: "medium",
      },
    ],
  },
]
