export interface Shop {
    id: string
    name: string
    owner: string
    description: string
    category: string
    image: string
    rating: number
    reviewCount: number
    location: string
    products: Product[]
}

export interface Product {
    id: string
    shopId: string
    name: string
    price: number
    description: string
    image: string
    category: string
    inStock: boolean
    details: string[]
    size?: "small" | "medium" | "large" | "tall" | "wide"
}

export interface CartItem {
    product: Product
    quantity: number
    shop: Shop
}

export const shops: Shop[] = [
    {
        id: "1",
        name: "Kultura Filipino Crafts",
        owner: "Maria Clara",
        description: "Authentic Filipino handicrafts, souvenirs, and traditional clothing showcasing the best of Filipino artistry.",
        category: "Handicrafts",
        image: "https://images.unsplash.com/photo-1596265371388-43edbaadab79?q=80&w=1000&auto=format&fit=crop",
        rating: 4.9,
        reviewCount: 342,
        location: "Intramuros, Manila",
        products: [
            {
                id: "p1",
                shopId: "1",
                name: "Classic Barong Tagalog",
                price: 2500.00,
                description: "Traditional formal embroidered shirt made from pineapple fiber (piña).",
                image: "https://images.unsplash.com/photo-1596265371388-43edbaadab79?q=80&w=1000&auto=format&fit=crop",
                category: "Clothing",
                inStock: true,
                details: ["Hand-embroidered", "Piña-Jusi fabric", "Formal wear"],
                size: "medium",
            },
            {
                id: "p2",
                shopId: "1",
                name: "Capiz Shell Parol",
                price: 1800.00,
                description: "Traditional star-shaped lantern made of capiz shells, perfect for Christmas.",
                image: "https://images.unsplash.com/photo-1606294898266-7e7774136d80?q=80&w=1000&auto=format&fit=crop",
                category: "Decor",
                inStock: true,
                details: ["Handcrafted", "LED lights included", "24 inches diameter"],
                size: "large",
            },
            {
                id: "p3",
                shopId: "1",
                name: "Abaca Tote Bag",
                price: 450.00,
                description: "Eco-friendly tote bag woven from durable abaca fibers.",
                image: "https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=1000&auto=format&fit=crop",
                category: "Accessories",
                inStock: true,
                details: ["Natural dye", "Leather handles", "Spacious interior"],
                size: "medium",
            },
            {
                id: "p4",
                shopId: "1",
                name: "Banig Sleeping Mat",
                price: 850.00,
                description: "Colorful handwoven sleeping mat from Samar.",
                image: "https://images.unsplash.com/photo-1617354366367-e925c481e843?q=80&w=1000&auto=format&fit=crop",
                category: "Home",
                inStock: true,
                details: ["Tikog grass", "Cool to sleep on", "Intricate patterns"],
                size: "large",
            },
            {
                id: "p5",
                shopId: "1",
                name: "Palawan South Sea Pearls",
                price: 3500.00,
                description: "Elegant gold stud earrings with genuine South Sea pearls.",
                image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop",
                category: "Jewelry",
                inStock: true,
                details: ["18k Gold settings", "Authentic pearls", "Certificate of authenticity"],
                size: "small",
            },
            {
                id: "p6",
                shopId: "1",
                name: "Jeepney Die-Cast Model",
                price: 350.00,
                description: "Miniature replica of the iconic Philippine Jeepney.",
                image: "https://images.unsplash.com/photo-1518413985552-32924194c738?q=80&w=1000&auto=format&fit=crop",
                category: "Souvenirs",
                inStock: true,
                details: ["Metal alloy", "Hand-painted", "Collectible item"],
                size: "small",
            },
        ],
    },
    {
        id: "2",
        name: "Batangas Brews & Beans",
        owner: "Mang Jose",
        description: "Strong and aromatic coffee beans sourced directly from farmers in Lipa, Batangas.",
        category: "Coffee & Food",
        image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=1000&auto=format&fit=crop",
        rating: 4.8,
        reviewCount: 189,
        location: "Lipa City, Batangas",
        products: [
            {
                id: "p7",
                shopId: "2",
                name: "Kapeng Barako (Ground)",
                price: 350.00,
                description: "Authentic Liberica coffee with a strong, bold flavor.",
                image: "https://images.unsplash.com/photo-1559525839-b184a4d698c7?q=80&w=1000&auto=format&fit=crop",
                category: "Coffee",
                inStock: true,
                details: ["500g pack", "Dark roast", "Freshly ground"],
                size: "medium",
            },
            {
                id: "p8",
                shopId: "2",
                name: "Tablea de Cacao",
                price: 180.00,
                description: "Pure cacao tablets for making traditional hot chocolate (tsokolate).",
                image: "https://images.unsplash.com/photo-1545663733-146313337922?q=80&w=1000&auto=format&fit=crop",
                category: "Food",
                inStock: true,
                details: ["100% Pure Cacao", "No sugar added", "Pack of 10 rolls"],
                size: "small",
            },
            {
                id: "p9",
                shopId: "2",
                name: "Civet Coffee (Kape Alamid)",
                price: 1500.00,
                description: "Rare and exotic coffee made from beans eaten and excreted by civet cats.",
                image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=1000&auto=format&fit=crop",
                category: "Coffee",
                inStock: true,
                details: ["100g jar", "Smooth taste", "Ethically sourced"],
                size: "small",
            },
            {
                id: "p10",
                shopId: "2",
                name: "Batangas Pure Honey",
                price: 250.00,
                description: "Raw, wild honey harvested from the forests of Batangas.",
                image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=1000&auto=format&fit=crop",
                category: "Food",
                inStock: true,
                details: ["Unpasteurized", "350ml bottle", "Wild harvested"],
                size: "medium",
            },
            {
                id: "p11",
                shopId: "2",
                name: "Wooden Coffee Scoop",
                price: 80.00,
                description: "Hand-carved wooden scoop for your coffee beans.",
                image: "https://images.unsplash.com/photo-1610376366687-3948a93ac13e?q=80&w=1000&auto=format&fit=crop",
                category: "Accessories",
                inStock: true,
                details: ["Acacia wood", "Food safe finish", "1 tbsp capacity"],
                size: "small",
            },
            {
                id: "p12",
                shopId: "2",
                name: "Kapeng Barako Beans",
                price: 320.00,
                description: "Whole roasted Liberica beans for grinding at home.",
                image: "https://images.unsplash.com/photo-1559525839-b184a4d698c7?q=80&w=1000&auto=format&fit=crop",
                category: "Coffee",
                inStock: true,
                details: ["500g pack", "Whole bean", "Aromatic"],
                size: "medium",
            },
        ],
    },
    {
        id: "3",
        name: "Cebu Lechon & Delicacies",
        owner: "Aling Puring",
        description: "Famous delicacies from the Queen City of the South, delivered to your doorstep.",
        category: "Food",
        image: "https://images.unsplash.com/photo-1624373408088-725354964259?q=80&w=1000&auto=format&fit=crop",
        rating: 4.7,
        reviewCount: 521,
        location: "Carcar, Cebu",
        products: [
            {
                id: "p13",
                shopId: "3",
                name: "Dried Mangoes",
                price: 220.00,
                description: "Sweet and chewy dried mango slices from Cebu.",
                image: "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?q=80&w=1000&auto=format&fit=crop",
                category: "Snacks",
                inStock: true,
                details: ["Export quality", "200g pack", "Sweet & tangy"],
                size: "medium",
            },
            {
                id: "p14",
                shopId: "3",
                name: "Otap Puff Pastry",
                price: 120.00,
                description: "Crispy, flaky, and sugary oval-shaped puff pastry.",
                image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=1000&auto=format&fit=crop",
                category: "Snacks",
                inStock: true,
                details: ["Original flavor", "Great with coffee", "Fragile handling"],
                size: "small",
            },
            {
                id: "p15",
                shopId: "3",
                name: "Rosquillos",
                price: 150.00,
                description: "Ring-shaped cookies that are a Cebuano favorite.",
                image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?q=80&w=1000&auto=format&fit=crop",
                category: "Snacks",
                inStock: true,
                details: ["Crunchy", "Lightly sweet", "Pasalubong favorite"],
                size: "medium",
            },
            {
                id: "p16",
                shopId: "3",
                name: "Chorizo de Cebu",
                price: 180.00,
                description: "Sweet and spicy native sausages, best fried.",
                image: "https://images.unsplash.com/photo-1595257841889-eca2678454e2?q=80&w=1000&auto=format&fit=crop",
                category: "Food",
                inStock: true,
                details: ["1 dozen", "Vacuum sealed", "Keep frozen"],
                size: "medium",
            },
            {
                id: "p17",
                shopId: "3",
                name: "Danggit (Dried Fish)",
                price: 350.00,
                description: "Salted and sun-dried rabbitfish, perfect for breakfast.",
                image: "https://images.unsplash.com/photo-1624373408088-725354964259?q=80&w=1000&auto=format&fit=crop",
                category: "Food",
                inStock: true,
                details: ["Unsalted variant", "Crispy when fried", "250g pack"],
                size: "medium",
            },
            {
                id: "p18",
                shopId: "3",
                name: "Ampao (Rice Krispies)",
                price: 80.00,
                description: "Sweet puffed rice bars with peanuts.",
                image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?q=80&w=1000&auto=format&fit=crop",
                category: "Snacks",
                inStock: true,
                details: ["Carcar specialty", "Crispy", "Pack of 10"],
                size: "small",
            },
        ],
    },
    {
        id: "4",
        name: "Marikina Shoe Hub",
        owner: "Mang Rolando",
        description: "World-class quality footwear handcrafted by Marikina's finest shoemakers.",
        category: "Fashion",
        image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop",
        rating: 4.6,
        reviewCount: 112,
        location: "Marikina City",
        products: [
            {
                id: "p19",
                shopId: "4",
                name: "Leather Sandals",
                price: 850.00,
                description: "Durable and stylish genuine leather sandals for men.",
                image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop",
                category: "Footwear",
                inStock: true,
                details: ["Genuine cowhide", "Rubber sole", "Hand-stitched"],
                size: "medium",
            },
            {
                id: "p20",
                shopId: "4",
                name: "School Shoes (Black)",
                price: 1200.00,
                description: "Classic black leather shoes for students.",
                image: "https://images.unsplash.com/photo-1512374382149-233c42b6a83b?q=80&w=1000&auto=format&fit=crop",
                category: "Footwear",
                inStock: true,
                details: ["Durable leather", "Comfort insole", "Standard school regulation"],
                size: "medium",
            },
            {
                id: "p21",
                shopId: "4",
                name: "Marikina Loafers",
                price: 1500.00,
                description: "Comfortable slip-on loafers for casual or office wear.",
                image: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?q=80&w=1000&auto=format&fit=crop",
                category: "Footwear",
                inStock: true,
                details: ["Soft leather", "Penny loafer style", "Available in brown/black"],
                size: "medium",
            },
            {
                id: "p22",
                shopId: "4",
                name: "Faux Snake Skin Boots",
                price: 2200.00,
                description: "Stylish ankle boots with a snake skin texture.",
                image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop",
                category: "Footwear",
                inStock: true,
                details: ["Synthetic leather", "High heel", "Side zipper"],
                size: "medium",
            },
            {
                id: "p23",
                shopId: "4",
                name: "Leather Belt",
                price: 450.00,
                description: "Full grain leather belt to match your shoes.",
                image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?q=80&w=1000&auto=format&fit=crop",
                category: "Accessories",
                inStock: true,
                details: ["Genuine leather", "Heavy duty buckle", "Adjustable length"],
                size: "large",
            },
            {
                id: "p24",
                shopId: "4",
                name: "Canvas Sneakers",
                price: 950.00,
                description: "Locally made canvas sneakers, comfortable for daily use.",
                image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1000&auto=format&fit=crop",
                category: "Footwear",
                inStock: true,
                details: ["Canvas upper", "Vulcanized rubber sole", "Unisex design"],
                size: "medium",
            },
        ],
    },
    {
        id: "5",
        name: "Baguio Weaves & Greens",
        owner: "Manang Imee",
        description: "Fresh produce and traditional weaves from the Summer Capital of the Philippines.",
        category: "Regional Specialties",
        image: "https://images.unsplash.com/photo-1595855709940-577268a29194?q=80&w=1000&auto=format&fit=crop",
        rating: 5.0,
        reviewCount: 245,
        location: "Baguio City",
        products: [
            {
                id: "p25",
                shopId: "5",
                name: "Inabel Blanket",
                price: 1200.00,
                description: "Handwoven Ilocano blanket known for its durability and warmth.",
                image: "https://images.unsplash.com/photo-1595855709940-577268a29194?q=80&w=1000&auto=format&fit=crop",
                category: "Home",
                inStock: true,
                details: ["Cotton blend", "Traditional patterns", "Queen size"],
                size: "large",
            },
            {
                id: "p26",
                shopId: "5",
                name: "Strawberry Jam",
                price: 250.00,
                description: "Homemade jam with whole strawberries from La Trinidad.",
                image: "https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?q=80&w=1000&auto=format&fit=crop",
                category: "Food",
                inStock: true,
                details: ["Whole berries", "Less sugar", "12oz jar"],
                size: "medium",
            },
            {
                id: "p27",
                shopId: "5",
                name: "Ube Jam (Halaya)",
                price: 320.00,
                description: "Creamy purple yam jam, a classic Baguio pasalubong.",
                image: "https://images.unsplash.com/photo-1616429388336-62674c0c167f?q=80&w=1000&auto=format&fit=crop",
                category: "Food",
                inStock: true,
                details: ["Real Ube", "Creamy texture", "Good Shepherd style"],
                size: "medium",
            },
            {
                id: "p28",
                shopId: "5",
                name: "Pine Wood Carving",
                price: 450.00,
                description: "Intricate wood carving of an eagle made from Benguet pine.",
                image: "https://images.unsplash.com/photo-1589820296156-2454bb8a4aa2?q=80&w=1000&auto=format&fit=crop",
                category: "Decor",
                inStock: true,
                details: ["Hand-carved", "Varnished", "Desk display size"],
                size: "small",
            },
            {
                id: "p29",
                shopId: "5",
                name: "Fresh Strawberries",
                price: 400.00,
                description: "Basket of freshly picked sweet strawberries.",
                image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?q=80&w=1000&auto=format&fit=crop",
                category: "Food",
                inStock: true,
                details: ["1kg basket", "Sweet variety", "Farm fresh"],
                size: "medium",
            },
            {
                id: "p30",
                shopId: "5",
                name: "Sagada Oranges",
                price: 150.00,
                description: "Sweet and juicy oranges grown in the highlands of Sagada.",
                image: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?q=80&w=1000&auto=format&fit=crop",
                category: "Food",
                inStock: true,
                details: ["1kg pack", "Seedless variety", "Vitamin C rich"],
                size: "medium",
            },
        ],
    },
]