export interface Shop {
    id: string
    name: string
    owner: string
    description: string
    category: string
    image: string
    rating: number
    reviewCount: number
    location: string
    products: Product[]
}

export interface Product {
    id: string
    shopId: string
    name: string
    price: number
    description: string
    image: string
    category: string
    inStock: boolean
    details: string[]
    size?: "small" | "medium" | "large" | "tall" | "wide"
}

export interface CartItem {
    product: Product
    quantity: number
    shop: Shop
}

export const shops: Shop[] = [
    {
        id: "1",
        name: "Green Thumb Gardens",
        owner: "Maria Santos",
        description: "Handcrafted succulent arrangements and organic herbs grown with love in our backyard greenhouse.",
        category: "Plants & Garden",
        image: "/greenhouse-with-plants-and-succulents.jpg",
        rating: 4.9,
        reviewCount: 127,
        location: "Downtown Market",
        products: [
            {
                id: "p1",
                shopId: "1",
                name: "Mini Succulent Trio",
                price: 24.99,
                description: "Three adorable succulents in handmade ceramic pots",
                image: "/three-small-succulents-in-ceramic-pots.jpg",
                category: "Succulents",
                inStock: true,
                details: ["Includes care guide", "Hand-painted pots", "Low maintenance"],
                size: "large",
            },
            {
                id: "p2",
                shopId: "1",
                name: "Herb Garden Kit",
                price: 34.99,
                description: "Basil, mint, and rosemary starter kit with organic soil",
                image: "/herb-garden-kit-basil-mint-rosemary.jpg",
                category: "Herbs",
                inStock: true,
                details: ["Organic seeds", "Biodegradable pots", "Instruction booklet"],
                size: "small",
            },
            {
                id: "p3",
                shopId: "1",
                name: "Hanging Terrarium",
                price: 45.0,
                description: "Glass terrarium with air plants and decorative stones",
                image: "/glass-hanging-terrarium-with-air-plants.jpg",
                category: "Terrariums",
                inStock: true,
                details: ["Hand-blown glass", "Natural stones", "Includes mounting hook"],
                size: "tall",
            },
            {
                id: "p4",
                shopId: "1",
                name: "Cactus Collection",
                price: 19.99,
                description: "Set of 4 mini cacti in terracotta pots",
                image: "/mini-cactus-collection-terracotta-pots.jpg",
                category: "Cacti",
                inStock: true,
                details: ["Drought tolerant", "Includes care card", "Perfect for beginners"],
                size: "small",
            },
            {
                id: "p5",
                shopId: "1",
                name: "Monstera Plant",
                price: 55.0,
                description: "Beautiful monstera deliciosa in woven basket",
                image: "/monstera-plant-in-woven-basket.jpg",
                category: "Indoor Plants",
                inStock: true,
                details: ["Air purifying", "Low light tolerant", "Pet friendly"],
                size: "wide",
            },
            {
                id: "p6",
                shopId: "1",
                name: "Lavender Bundle",
                price: 12.0,
                description: "Dried lavender stems tied with twine",
                image: "/dried-lavender-bundle-tied-with-twine.jpg",
                category: "Dried Flowers",
                inStock: true,
                details: ["Naturally dried", "Fragrant", "Lasts months"],
                size: "small",
            },
        ],
    },
    {
        id: "2",
        name: "Artisan Bread Co.",
        owner: "Chef Paolo",
        description: "Traditional sourdough and artisan breads baked fresh every morning using family recipes.",
        category: "Bakery",
        image: "/artisan-bakery-with-fresh-bread-display.jpg",
        rating: 4.8,
        reviewCount: 203,
        location: "East Side Market",
        products: [
            {
                id: "p7",
                shopId: "2",
                name: "Classic Sourdough Loaf",
                price: 8.5,
                description: "24-hour fermented sourdough with crispy crust",
                image: "/rustic-sourdough-loaf.png",
                category: "Bread",
                inStock: true,
                details: ["Natural fermentation", "No preservatives", "Best within 3 days"],
                size: "large",
            },
            {
                id: "p8",
                shopId: "2",
                name: "Olive Focaccia",
                price: 12.0,
                description: "Italian focaccia with kalamata olives and rosemary",
                image: "/focaccia-bread-with-olives-and-rosemary.jpg",
                category: "Bread",
                inStock: true,
                details: ["Extra virgin olive oil", "Sea salt finish", "Serves 4-6"],
                size: "small",
            },
            {
                id: "p9",
                shopId: "2",
                name: "Baguette",
                price: 5.0,
                description: "Traditional French baguette with golden crust",
                image: "/french-baguette-golden-crust.jpg",
                category: "Bread",
                inStock: true,
                details: ["Crispy crust", "Soft interior", "Best same day"],
                size: "tall",
            },
            {
                id: "p10",
                shopId: "2",
                name: "Croissant Pack",
                price: 15.0,
                description: "Box of 6 buttery French croissants",
                image: "/butter-croissants-in-box.jpg",
                category: "Pastry",
                inStock: true,
                details: ["French butter", "Flaky layers", "Freezer friendly"],
                size: "small",
            },
            {
                id: "p11",
                shopId: "2",
                name: "Cinnamon Rolls",
                price: 18.0,
                description: "Fresh baked cinnamon rolls with cream cheese frosting",
                image: "/cinnamon-rolls-with-frosting.jpg",
                category: "Sweet",
                inStock: true,
                details: ["Cream cheese icing", "Pack of 4", "Reheat to serve"],
                size: "wide",
            },
            {
                id: "p12",
                shopId: "2",
                name: "Pretzel Bites",
                price: 7.0,
                description: "Soft pretzel bites with cheese dip",
                image: "/soft-pretzel-bites-with-cheese-dip.jpg",
                category: "Snacks",
                inStock: true,
                details: ["Served warm", "Includes dip", "Great for sharing"],
                size: "small",
            },
        ],
    },
    {
        id: "3",
        name: "Woven Stories",
        owner: "Emma & Jake",
        description: "Handwoven textiles, macramé wall art, and boho home décor made from sustainable materials.",
        category: "Home & Crafts",
        image: "/boho-macrame-and-textile-craft-booth.jpg",
        rating: 4.7,
        reviewCount: 89,
        location: "Arts District",
        products: [
            {
                id: "p13",
                shopId: "3",
                name: "Macramé Wall Hanging",
                price: 65.0,
                description: "Large bohemian wall piece with natural cotton cord",
                image: "/large-macrame-wall-hanging-boho-style.jpg",
                category: "Wall Art",
                inStock: true,
                details: ["100% cotton", "36 inches wide", "Driftwood rod included"],
                size: "large",
            },
            {
                id: "p14",
                shopId: "3",
                name: "Woven Plant Hanger",
                price: 28.0,
                description: "Minimalist plant hanger for 4-6 inch pots",
                image: "/macrame-plant-hanger-minimalist.jpg",
                category: "Plant Holders",
                inStock: true,
                details: ["Fits 4-6 inch pots", "Indoor/outdoor", "40 inches total length"],
                size: "small",
            },
            {
                id: "p15",
                shopId: "3",
                name: "Tassel Garland",
                price: 22.0,
                description: "Colorful cotton tassel garland for walls or parties",
                image: "/colorful-tassel-garland-decoration.jpg",
                category: "Decor",
                inStock: true,
                details: ["6 feet long", "Handmade tassels", "Mix of colors"],
                size: "tall",
            },
            {
                id: "p16",
                shopId: "3",
                name: "Woven Basket Set",
                price: 45.0,
                description: "Set of 3 nesting storage baskets",
                image: "/woven-storage-baskets-set.jpg",
                category: "Storage",
                inStock: true,
                details: ["Natural seagrass", "3 sizes", "Handwoven"],
                size: "small",
            },
            {
                id: "p17",
                shopId: "3",
                name: "Boho Pillow Set",
                price: 55.0,
                description: "Set of two handwoven throw pillows with tassels",
                image: "/placeholder.svg?height=150&width=300",
                category: "Textiles",
                inStock: true,
                details: ["Inserts included", "18x18 inches", "Spot clean only"],
                size: "wide",
            },
            {
                id: "p18",
                shopId: "3",
                name: "Dream Catcher",
                price: 35.0,
                description: "Handmade dream catcher with feathers",
                image: "/placeholder.svg?height=150&width=150",
                category: "Wall Art",
                inStock: true,
                details: ["Natural feathers", "12 inch ring", "Ready to hang"],
                size: "small",
            },
        ],
    },
    {
        id: "4",
        name: "Honeybee Haven",
        owner: "The Nguyen Family",
        description: "Raw local honey, beeswax candles, and natural skincare products from our family apiary.",
        category: "Natural Products",
        image: "/placeholder.svg?height=400&width=400",
        rating: 5.0,
        reviewCount: 156,
        location: "Farmers Market",
        products: [
            {
                id: "p19",
                shopId: "4",
                name: "Raw Wildflower Honey",
                price: 18.0,
                description: "16oz jar of unfiltered local wildflower honey",
                image: "/placeholder.svg?height=200&width=200",
                category: "Honey",
                inStock: true,
                details: ["Unfiltered", "Local wildflowers", "Glass jar"],
                size: "large",
            },
            {
                id: "p20",
                shopId: "4",
                name: "Beeswax Candle Set",
                price: 32.0,
                description: "Set of 3 hand-rolled beeswax pillar candles",
                image: "/placeholder.svg?height=150&width=150",
                category: "Candles",
                inStock: true,
                details: ["Pure beeswax", "Cotton wicks", "30+ hour burn time each"],
                size: "small",
            },
            {
                id: "p21",
                shopId: "4",
                name: "Honeycomb Frame",
                price: 28.0,
                description: "Fresh honeycomb still in wooden frame",
                image: "/placeholder.svg?height=250&width=150",
                category: "Honey",
                inStock: true,
                details: ["Edible wax", "Raw unprocessed", "Approx 1lb"],
                size: "tall",
            },
            {
                id: "p22",
                shopId: "4",
                name: "Honey Lip Balm Trio",
                price: 15.0,
                description: "Three flavored lip balms: honey, lavender, mint",
                image: "/placeholder.svg?height=150&width=150",
                category: "Skincare",
                inStock: true,
                details: ["All natural", "Beeswax base", "No artificial colors"],
                size: "small",
            },
            {
                id: "p23",
                shopId: "4",
                name: "Honey Gift Box",
                price: 48.0,
                description: "Curated gift box with honey, candle, and soap",
                image: "/placeholder.svg?height=150&width=300",
                category: "Gifts",
                inStock: true,
                details: ["Gift wrapped", "Card included", "Mix of products"],
                size: "wide",
            },
            {
                id: "p24",
                shopId: "4",
                name: "Propolis Tincture",
                price: 22.0,
                description: "Bee propolis extract for immune support",
                image: "/placeholder.svg?height=150&width=150",
                category: "Wellness",
                inStock: true,
                details: ["30ml bottle", "Dropper included", "Take daily"],
                size: "small",
            },
        ],
    },
    {
        id: "5",
        name: "Vintage Vinyl & More",
        owner: "DJ Marcus",
        description: "Curated collection of vintage records, band tees, and music memorabilia from the 60s to 90s.",
        category: "Music & Vintage",
        image: "/placeholder.svg?height=400&width=400",
        rating: 4.6,
        reviewCount: 74,
        location: "Old Town Square",
        products: [
            {
                id: "p25",
                shopId: "5",
                name: "Mystery Vinyl Bundle",
                price: 40.0,
                description: "5 hand-picked vinyl records based on your taste",
                image: "/placeholder.svg?height=200&width=200",
                category: "Records",
                inStock: true,
                details: ["5 records", "Graded VG+ or better", "Genre of your choice"],
                size: "large",
            },
            {
                id: "p26",
                shopId: "5",
                name: "Vintage Band Tee",
                price: 35.0,
                description: "Authentic vintage concert tee from the 80s/90s",
                image: "/placeholder.svg?height=150&width=150",
                category: "Apparel",
                inStock: true,
                details: ["Authentic vintage", "Sizes vary", "Some wear adds character"],
                size: "small",
            },
            {
                id: "p27",
                shopId: "5",
                name: "Classic Rock LP",
                price: 25.0,
                description: "Original pressing classic rock album",
                image: "/placeholder.svg?height=250&width=150",
                category: "Records",
                inStock: true,
                details: ["Original pressing", "Includes sleeve", "VG+ condition"],
                size: "tall",
            },
            {
                id: "p28",
                shopId: "5",
                name: "Record Display Frame",
                price: 25.0,
                description: "Wall-mounted display frame for your favorite album",
                image: "/placeholder.svg?height=150&width=150",
                category: "Accessories",
                inStock: true,
                details: ["Fits standard LPs", "Easy swap design", "Mounting hardware included"],
                size: "small",
            },
            {
                id: "p29",
                shopId: "5",
                name: "Cassette Tape Set",
                price: 20.0,
                description: "Set of 5 vintage cassette tapes",
                image: "/placeholder.svg?height=150&width=300",
                category: "Cassettes",
                inStock: true,
                details: ["Mixed genres", "Tested working", "80s/90s era"],
                size: "wide",
            },
            {
                id: "p30",
                shopId: "5",
                name: "Guitar Picks Tin",
                price: 12.0,
                description: "Vintage-style tin with 20 assorted picks",
                image: "/placeholder.svg?height=150&width=150",
                category: "Accessories",
                inStock: true,
                details: ["20 picks", "Various gauges", "Collectible tin"],
                size: "small",
            },
        ],
    },
]